export const REGISTER_ACCOUNT_START = 'REGISTER_ACCOUNT_START'
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS'
export const REGISTER_ACCOUNT_FAILURE = 'REGISTER_ACCOUNT_FAILURE'

export const LOGIN_ACCOUNT_START = 'LOGIN_ACCOUNT_START'
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS'
export const LOGIN_ACCOUNT_FAILURE = 'LOGIN_ACCOUNT_FAILURE'

export const ADD_STORE_START = 'ADD_STORE_START'
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS'
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE'

export const GET_STORES_START= 'GET_STORES_START'
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS'
export const GET_STORES_FAILURE = 'GET_STORES_FAILURE'


