export const REGISTER_ACCOUNT_START = 'REGISTER_ACCOUNT_START'
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS'
export const REGISTER_ACCOUNT_FAILURE = 'REGISTER_ACCOUNT_FAILURE'

export const LOGIN_ACCOUNT_START = 'LOGIN_ACCOUNT_START'
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS'
export const LOGIN_ACCOUNT_FAILURE = 'LOGIN_ACCOUNT_FAILURE'

export const GET_STORE_START = 'GET_STORE_START'
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS'
export const GET_STORE_FAILURE = 'GET_STORE_FAILURE'

export const ADD_STORE_START = 'ADD_STORE_START'
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS'
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE'

export const GET_STORES_START= 'GET_STORES_START'
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS'
export const GET_STORES_FAILURE = 'GET_STORES_FAILURE'

export const EDIT_STORE_START = 'EDIT_STORE_START'
export const EDIT_STORE_SUCCESS = 'EDIT_STORE_SUCCESS'
export const EDIT_STORE_FAILURE = 'EDIT_STORE_FAILURE'

export const DELETE_STORE_START = 'DELETE_STORE_START'
export const DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS'
export const DELETE_STORE_FAILURE = 'DELETE_STORE_FAILURE'

export const ADD_ITEM_START = 'ADD_ITEM_START'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'



